### ISSUE TITLE
tei-xml instructions

### ISSUE THREAD

**Issue by tkhagan** [dig-eg-gaz/dig-eg-gaz.github.io#3]
I reviewed the TEI-xml instructions and I have a few comments:

step 2: 
- state that you want them to create the new document in atom or oxygen because you then jump to uploading it into the repository and in the past they have only uploaded from their word processing files. 
  -remove the word "and" before "save it to a new folder in your personal repository <-do you mean github or a file folder they create to save their work in atom?). 

Step 3: 
- say where the editing is being done. the may think in github if your previous instructions work flow requires them to end there when they saved to their repository so let them know they need to go back to atom/oxygen. It best to be clear
  -make clear that the text format of date is month and year (ie January 1905)
  -I think you may need to add a step about changing the day of the week and date in the header of the text body
  -Also, i noticed there is a tag "scope=advertisement". Not sure if that is supposed to be there or not.

Step 4:
-on a pc it is alt+ctrl+.

**Comment by whanley** [comment]
Thanks for these, Tara. I've finally incorporated them.
